/// Maps food names (from FatSecret or any API) to the most fitting
/// Unicode emoji using keyword matching.
///
/// Algorithm:
///   1. Normalize the food name to lowercase.
///   2. Try multi-word phrases first (more specific) — longest match wins.
///   3. Fall back to single-word keywords.
///   4. Return 🍽️ if nothing matches.
///
/// No API calls. Works offline. Zero cost. Android 8+ (API 26) supports
/// all emojis in this list.
class FoodEmojiHelper {
  FoodEmojiHelper._();

  // ── Ordered map: multi-word phrases first, then single keywords ───────────
  // Keep multi-word entries at the top so they are matched before their
  // component words (e.g. "egg fried rice" → 🍳 not just 🥚).
  static const Map<String, String> _map = {
    // ── Multi-word phrases ─────────────────────────────────────────────────
    'egg fried rice'    : '🍳',
    'fried rice'        : '🍚',
    'white rice'        : '🍚',
    'brown rice'        : '🍚',
    'basmati rice'      : '🍚',
    'jasmine rice'      : '🍚',
    'sticky rice'       : '🍚',
    'coconut rice'      : '🍚',
    'rice bowl'         : '🍚',
    'fried egg'         : '🍳',
    'scrambled egg'     : '🍳',
    'boiled egg'        : '🥚',
    'poached egg'       : '🥚',
    'egg white'         : '🥚',
    'egg yolk'          : '🥚',
    'deviled egg'       : '🥚',
    'ice cream'         : '🍦',
    'french fries'      : '🍟',
    'hot dog'           : '🌭',
    'hot chocolate'     : '☕',
    'green tea'         : '🍵',
    'black tea'         : '🍵',
    'iced tea'          : '🍵',
    'milk tea'          : '🍵',
    'bubble tea'        : '🧋',
    'boba tea'          : '🧋',
    'olive oil'         : '🫒',
    'coconut oil'       : '🥥',
    'sweet potato'      : '🍠',
    'peanut butter'     : '🥜',
    'almond butter'     : '🥜',
    'kidney bean'       : '🫘',
    'black bean'        : '🫘',
    'pinto bean'        : '🫘',
    'soy milk'          : '🥛',
    'whole milk'        : '🥛',
    'skim milk'         : '🥛',
    'oat milk'          : '🥛',
    'almond milk'       : '🥛',
    'coconut milk'      : '🥥',
    'greek yogurt'      : '🥛',
    'frozen yogurt'     : '🍦',
    'cottage cheese'    : '🧀',
    'cream cheese'      : '🧀',
    'cheddar cheese'    : '🧀',
    'mozzarella'        : '🧀',
    'parmesan'          : '🧀',
    'whipped cream'     : '🍦',
    'sour cream'        : '🥛',
    'mac and cheese'    : '🍝',
    'macaroni and cheese': '🍝',
    'grilled chicken'   : '🍗',
    'roast chicken'     : '🍗',
    'chicken breast'    : '🍗',
    'chicken thigh'     : '🍗',
    'chicken wing'      : '🍗',
    'chicken nugget'    : '🍗',
    'chicken curry'     : '🍛',
    'chicken biryani'   : '🍛',
    'chicken tikka'     : '🍛',
    'butter chicken'    : '🍛',
    'chicken soup'      : '🥣',
    'chicken salad'     : '🥗',
    'tuna salad'        : '🥗',
    'caesar salad'      : '🥗',
    'green salad'       : '🥗',
    'fruit salad'       : '🍇',
    'beef steak'        : '🥩',
    'ground beef'       : '🥩',
    'beef burger'       : '🍔',
    'lamb chop'         : '🥩',
    'pork chop'         : '🥩',
    'pork belly'        : '🥓',
    'beef curry'        : '🍛',
    'lamb curry'        : '🍛',
    'fish curry'        : '🍛',
    'dal makhani'       : '🫘',
    'yellow dal'        : '🫘',
    'dal tadka'         : '🫘',
    'chana masala'      : '🫘',
    'rajma'             : '🫘',
    'aloo gobi'         : '🥔',
    'palak paneer'      : '🧀',
    'paneer tikka'      : '🧀',
    'matar paneer'      : '🧀',
    'gulab jamun'       : '🍮',
    'kheer'             : '🍮',
    'halwa'             : '🍮',
    'ladoo'             : '🍬',
    'barfi'             : '🍬',
    'rasmalai'          : '🍮',
    'gajar halwa'       : '🥕',
    'samosa'            : '🥟',
    'vada pav'          : '🫓',
    'pav bhaji'         : '🫓',
    'masala dosa'       : '🥞',
    'plain dosa'        : '🥞',
    'rava dosa'         : '🥞',
    'idli sambar'       : '🥟',
    'aloo paratha'      : '🫓',
    'cheese paratha'    : '🫓',
    'whole wheat bread' : '🍞',
    'white bread'       : '🍞',
    'sourdough bread'   : '🍞',
    'multigrain bread'  : '🍞',
    'garlic bread'      : '🍞',
    'banana bread'      : '🍌',
    'french toast'      : '🍳',
    'avocado toast'     : '🥑',
    'peanut butter toast': '🥜',
    'tomato soup'       : '🍅',
    'pumpkin soup'      : '🎃',
    'mushroom soup'     : '🍄',
    'lentil soup'       : '🫘',
    'chicken noodle soup': '🍜',
    'miso soup'         : '🍵',
    'vegetable soup'    : '🥣',
    'potato soup'       : '🥔',
    'minestrone'        : '🥣',
    'tomato sauce'      : '🍅',
    'pasta sauce'       : '🍝',
    'soy sauce'         : '🫙',
    'fish sauce'        : '🐟',
    'hot sauce'         : '🌶️',
    'BBQ sauce'         : '🍖',
    'teriyaki sauce'    : '🍱',
    'orange juice'      : '🍊',
    'apple juice'       : '🍎',
    'mango juice'       : '🥭',
    'tomato juice'      : '🍅',
    'grape juice'       : '🍇',
    'cranberry juice'   : '🫐',
    'protein shake'     : '💪',
    'protein powder'    : '💪',
    'protein bar'       : '💪',
    'energy bar'        : '⚡',
    'granola bar'       : '🥣',
    'dark chocolate'    : '🍫',
    'milk chocolate'    : '🍫',
    'white chocolate'   : '🍫',
    'chocolate cake'    : '🎂',
    'cheesecake'        : '🍰',
    'birthday cake'     : '🎂',
    'carrot cake'       : '🥕',
    'apple pie'         : '🥧',
    'pumpkin pie'       : '🎃',
    'blueberry muffin'  : '🫐',
    'chocolate muffin'  : '🍫',
    'corn tortilla'     : '🌮',
    'flour tortilla'    : '🌯',
    'spring roll'       : '🥟',
    'egg roll'          : '🥟',
    'dim sum'           : '🥟',
    'beef noodle'       : '🍜',
    'pad thai'          : '🍜',
    'lo mein'           : '🍜',
    'chow mein'         : '🍜',
    'fried noodle'      : '🍜',
    'instant noodle'    : '🍜',
    'cheese pizza'      : '🍕',
    'pepperoni pizza'   : '🍕',
    'veggie pizza'      : '🍕',
    'mixed nuts'        : '🥜',
    'trail mix'         : '🥜',
    'potato chips'      : '🍟',
    'corn chips'        : '🍟',
    'rice cake'         : '🍘',
    'energy drink'      : '⚡',
    'sports drink'      : '🏃',
    'coconut water'     : '🥥',

    // ── Single keywords ────────────────────────────────────────────────────
    // Proteins
    'chicken'     : '🍗',
    'turkey'      : '🍗',
    'duck'        : '🍗',
    'quail'       : '🍗',
    'beef'        : '🥩',
    'steak'       : '🥩',
    'mutton'      : '🥩',
    'lamb'        : '🥩',
    'veal'        : '🥩',
    'pork'        : '🥩',
    'bacon'       : '🥓',
    'ham'         : '🥓',
    'pepperoni'   : '🍕',
    'sausage'     : '🌭',
    'salami'      : '🌭',
    'meatball'    : '🍝',
    'fish'        : '🐟',
    'salmon'      : '🐟',
    'tuna'        : '🐟',
    'cod'         : '🐟',
    'tilapia'     : '🐟',
    'trout'       : '🐟',
    'sardine'     : '🐟',
    'mackerel'    : '🐟',
    'halibut'     : '🐟',
    'anchovy'     : '🐟',
    'herring'     : '🐟',
    'carp'        : '🐟',
    'shrimp'      : '🦐',
    'prawn'       : '🦐',
    'crab'        : '🦀',
    'lobster'     : '🦞',
    'squid'       : '🦑',
    'octopus'     : '🐙',
    'oyster'      : '🦪',
    'clam'        : '🦪',
    'scallop'     : '🦪',
    'mussel'      : '🦪',
    'tofu'        : '🧆',
    'tempeh'      : '🧆',
    'seitan'      : '🧆',
    'egg'         : '🥚',
    'paneer'      : '🧀',

    // Dairy
    'milk'        : '🥛',
    'yogurt'      : '🥛',
    'curd'        : '🥛',
    'kefir'       : '🥛',
    'cheese'      : '🧀',
    'butter'      : '🧈',
    'ghee'        : '🧈',
    'cream'       : '🍦',
    'lassi'       : '🥛',

    // Fruits
    'apple'       : '🍎',
    'banana'      : '🍌',
    'orange'      : '🍊',
    'mango'       : '🥭',
    'grape'       : '🍇',
    'strawberry'  : '🍓',
    'watermelon'  : '🍉',
    'pineapple'   : '🍍',
    'cherry'      : '🍒',
    'peach'       : '🍑',
    'pear'        : '🍐',
    'kiwi'        : '🥝',
    'lemon'       : '🍋',
    'lime'        : '🍋',
    'coconut'     : '🥥',
    'blueberry'   : '🫐',
    'raspberry'   : '🍓',
    'blackberry'  : '🫐',
    'pomegranate' : '🍎',
    'papaya'      : '🥭',
    'guava'       : '🍈',
    'lychee'      : '🍒',
    'avocado'     : '🥑',
    'fig'         : '🍇',
    'date'        : '🌴',
    'plum'        : '🍇',
    'apricot'     : '🍑',
    'passion fruit':'🍈',
    'dragon fruit': '🍈',
    'jackfruit'   : '🍈',
    'melon'       : '🍈',
    'cantaloupe'  : '🍈',
    'honeydew'    : '🍈',
    'grapefruit'  : '🍊',
    'clementine'  : '🍊',
    'tangerine'   : '🍊',
    'nectarine'   : '🍑',

    // Vegetables
    'tomato'      : '🍅',
    'carrot'      : '🥕',
    'broccoli'    : '🥦',
    'corn'        : '🌽',
    'potato'      : '🥔',
    'onion'       : '🧅',
    'garlic'      : '🧄',
    'pepper'      : '🫑',
    'capsicum'    : '🫑',
    'bell pepper' : '🫑',
    'jalapeño'    : '🌶️',
    'chilli'      : '🌶️',
    'chili'       : '🌶️',
    'spinach'     : '🥬',
    'lettuce'     : '🥬',
    'kale'        : '🥬',
    'cabbage'     : '🥬',
    'bok choy'    : '🥬',
    'cucumber'    : '🥒',
    'zucchini'    : '🥒',
    'eggplant'    : '🍆',
    'aubergine'   : '🍆',
    'brinjal'     : '🍆',
    'pumpkin'     : '🎃',
    'squash'      : '🎃',
    'beetroot'    : '🫚',
    'beet'        : '🫚',
    'mushroom'    : '🍄',
    'asparagus'   : '🥦',
    'celery'      : '🥬',
    'cauliflower' : '🥦',
    'leek'        : '🧅',
    'radish'      : '🌱',
    'turnip'      : '🌱',
    'okra'        : '🌱',
    'artichoke'   : '🌿',
    'pea'         : '🫛',
    'bean'        : '🫘',
    'lentil'      : '🫘',
    'chickpea'    : '🫘',
    'dal'         : '🫘',
    'edamame'     : '🫛',
    'soybean'     : '🫘',

    // Grains & Bread
    'rice'        : '🍚',
    'bread'       : '🍞',
    'toast'       : '🍞',
    'baguette'    : '🥖',
    'croissant'   : '🥐',
    'bagel'       : '🥯',
    'pretzel'     : '🥨',
    'roti'        : '🫓',
    'chapati'     : '🫓',
    'naan'        : '🫓',
    'pita'        : '🫓',
    'tortilla'    : '🫓',
    'wrap'        : '🌯',
    'dosa'        : '🥞',
    'idli'        : '🥟',
    'oat'         : '🥣',
    'oatmeal'     : '🥣',
    'porridge'    : '🥣',
    'granola'     : '🥣',
    'muesli'      : '🥣',
    'cereal'      : '🥣',
    'corn flakes' : '🥣',
    'quinoa'      : '🌾',
    'millet'      : '🌾',
    'wheat'       : '🌾',
    'flour'       : '🌾',
    'barley'      : '🌾',
    'pasta'       : '🍝',
    'spaghetti'   : '🍝',
    'penne'       : '🍝',
    'linguine'    : '🍝',
    'fettuccine'  : '🍝',
    'lasagna'     : '🍝',
    'noodle'      : '🍜',
    'udon'        : '🍜',
    'soba'        : '🍜',
    'vermicelli'  : '🍜',
    'macaroni'    : '🍝',
    'gnocchi'     : '🍝',
    'couscous'    : '🌾',
    'pancake'     : '🥞',
    'waffle'      : '🧇',
    'crepe'       : '🥞',

    // Dishes
    'biryani'     : '🍛',
    'curry'       : '🍛',
    'pulao'       : '🍚',
    'pilaf'       : '🍚',
    'khichdi'     : '🍚',
    'risotto'     : '🍚',
    'paella'      : '🥘',
    'soup'        : '🥣',
    'stew'        : '🥘',
    'broth'       : '🥣',
    'bisque'      : '🥣',
    'chowder'     : '🥣',
    'salad'       : '🥗',
    'coleslaw'    : '🥗',
    'sushi'       : '🍱',
    'sashimi'     : '🐟',
    'maki'        : '🍱',
    'bento'       : '🍱',
    'dumpling'    : '🥟',
    'gyoza'       : '🥟',
    'wonton'      : '🥟',
    'pakora'      : '🧆',
    'bhaji'       : '🧆',
    'kebab'       : '🥙',
    'tikka'       : '🍛',
    'korma'       : '🍛',
    'masala'      : '🍛',
    'vindaloo'    : '🍛',
    'saag'        : '🥬',
    'raita'       : '🥛',
    'chutney'     : '🫙',
    'pickle'      : '🥒',
    'kimchi'      : '🥬',
    'sauerkraut'  : '🥬',
    'hummus'      : '🫙',
    'guacamole'   : '🥑',
    'salsa'       : '🍅',
    'tzatziki'    : '🥛',
    'pesto'       : '🌿',
    'falafel'     : '🧆',
    'shawarma'    : '🥙',
    'gyro'        : '🥙',
    'taco'        : '🌮',
    'burrito'     : '🌯',
    'quesadilla'  : '🌮',
    'enchilada'   : '🌮',
    'nachos'      : '🧀',

    // Fast Food
    'burger'      : '🍔',
    'hamburger'   : '🍔',
    'cheeseburger': '🍔',
    'sandwich'    : '🥪',
    'sub'         : '🥪',
    'hotdog'      : '🌭',
    'pizza'       : '🍕',
    'fries'       : '🍟',
    'chips'       : '🍟',
    'nugget'      : '🍗',

    // Nuts & Seeds
    'almond'      : '🥜',
    'peanut'      : '🥜',
    'cashew'      : '🥜',
    'walnut'      : '🥜',
    'pistachio'   : '🥜',
    'hazelnut'    : '🥜',
    'macadamia'   : '🥜',
    'pecan'       : '🥜',
    'nut'         : '🥜',
    'sunflower seed':'🌻',
    'pumpkin seed': '🎃',
    'chia'        : '🌱',
    'flaxseed'    : '🌱',
    'sesame'      : '🌱',
    'hemp'        : '🌱',

    // Sweets & Desserts
    'chocolate'   : '🍫',
    'cake'        : '🎂',
    'cookie'      : '🍪',
    'biscuit'     : '🍪',
    'brownie'     : '🍫',
    'donut'       : '🍩',
    'doughnut'    : '🍩',
    'muffin'      : '🧁',
    'cupcake'     : '🧁',
    'pie'         : '🥧',
    'tart'        : '🥧',
    'pudding'     : '🍮',
    'custard'     : '🍮',
    'mousse'      : '🍮',
    'eclair'      : '🥐',
    'macaron'     : '🍪',
    'candy'       : '🍬',
    'sweet'       : '🍬',
    'gummy'       : '🍬',
    'marshmallow' : '🍬',
    'toffee'      : '🍬',
    'caramel'     : '🍮',
    'fudge'       : '🍫',
    'truffle'     : '🍫',
    'popsicle'    : '🍭',
    'lollipop'    : '🍭',
    'gelato'      : '🍨',
    'sorbet'      : '🍧',
    'parfait'     : '🍨',
    'tiramisu'    : '🍰',

    // Condiments & Extras
    'honey'       : '🍯',
    'jam'         : '🫙',
    'jelly'       : '🫙',
    'marmalade'   : '🫙',
    'syrup'       : '🍯',
    'ketchup'     : '🍅',
    'mustard'     : '🌻',
    'mayo'        : '🥚',
    'mayonnaise'  : '🥚',
    'sauce'       : '🫙',
    'dressing'    : '🫙',
    'vinegar'     : '🫙',
    'oil'         : '🫒',
    'salt'        : '🧂',
    'sugar'       : '🍬',
    'stevia'      : '🌿',
    'spice'       : '🌶️',
    'herb'        : '🌿',
    'mint'        : '🌿',
    'cinnamon'    : '🌿',
    'ginger'      : '🌱',
    'turmeric'    : '🌿',
    'cumin'       : '🌿',
    'coriander'   : '🌿',
    'basil'       : '🌿',
    'oregano'     : '🌿',
    'thyme'       : '🌿',
    'rosemary'    : '🌿',
    'parsley'     : '🌿',

    // Beverages
    'water'       : '💧',
    'coffee'      : '☕',
    'espresso'    : '☕',
    'latte'       : '☕',
    'cappuccino'  : '☕',
    'americano'   : '☕',
    'tea'         : '🍵',
    'chai'        : '🍵',
    'juice'       : '🧃',
    'smoothie'    : '🥤',
    'shake'       : '🥤',
    'milkshake'   : '🥤',
    'soda'        : '🥤',
    'cola'        : '🥤',
    'beer'        : '🍺',
    'wine'        : '🍷',
    'whiskey'     : '🥃',
    'vodka'       : '🍸',
    'rum'         : '🍸',
    'cocktail'    : '🍹',
    'kombucha'    : '🧃',
    'lemonade'    : '🍋',

    // Fitness / Supplements
    'protein'     : '💪',
    'whey'        : '💪',
    'supplement'  : '💊',
    'vitamin'     : '💊',
    'probiotic'   : '💊',
    'collagen'    : '💪',
    'creatine'    : '💪',
    'bcaa'        : '💪',
  };

  /// Returns the best emoji for [foodName].
  /// Checks multi-word phrases first, then single keywords.
  static String get(String foodName) {
    if (foodName.trim().isEmpty) return '🍽️';
    final lower = foodName.toLowerCase().trim();

    // 1. Multi-word phrases (more specific) — longest match wins
    final multiMatches = _map.keys
        .where((k) => k.contains(' ') && lower.contains(k))
        .toList()
      ..sort((a, b) => b.length.compareTo(a.length));
    if (multiMatches.isNotEmpty) return _map[multiMatches.first]!;

    // 2. Single-word keywords — longest match wins (avoids 'pea' matching 'peach')
    final singleMatches = _map.keys
        .where((k) => !k.contains(' ') && lower.contains(k))
        .toList()
      ..sort((a, b) => b.length.compareTo(a.length));
    if (singleMatches.isNotEmpty) return _map[singleMatches.first]!;

    return '🍽️';
  }
}
